### ISSUE TITLE
README has inconsistent onboarding JSON

### ISSUE THREAD

**Issue by brian-labelle** [adobe/commerce-integration-starter-kit#11]
### Expected Behaviour
The README's onboarding JSON example is inconsistent with the code. According to the code, there is not a separate set of actions for shipment. Shipment actions would fall under the order actions. When running the onboarding script, with the values in the README, it should pass without error.

### Actual Behaviour
Using the values from the README, it attempts to register shipments actions, but the code wants them to be under the order actions

Suggestion: remove the following from the readme
`"shipment": ["commerce", "backoffice"]`

**Comment by rojoangel** [comment]
@brian-labelle Thanks for reporting this issue
