### ISSUE TITLE
Onboarding Script creates entities that cannot pass frontend validation

### ISSUE THREAD

**Issue by brian-labelle** [adobe/commerce-integration-starter-kit#14]
The onboarding script will create event registrations with names that cannot not pass frontend validation. As a result, they cannot be modified in Adobe console without changing the name. 

The onboarding script adds the word 'Synchronization', which is capable of making the event registration name too long. 
The script can create them, but once you try to make changes in the UI, you cannot proceed until you change the name. That can cause them to fall out of sync with the starter kit code, and re-running the onboarding script with new registrations can cause duplicates

Example below:

<img width="647" alt="Screenshot 2024-07-19 at 1 12 04 PM" src="https://github.com/user-attachments/assets/5c282b20-6de4-4550-b4ae-868c7e4d5304">

**Comment by rojoangel** [comment]
Changes validated: the event registration name is now within the UI limits.

![EventRegistrationDetails](https://github.com/user-attachments/assets/52aa0183-6870-43c1-b09f-301e9b7cdda8)
