### ISSUE TITLE
Naming of SAP S/4HANA in the architecture.png

### ISSUE THREAD

**Issue by gregorwolf** [adobe/commerce-integration-starter-kit#20]
### Expected Behaviour

The correct name for the Backoffice System in the architecture.png should be "SAP S/4HANA"

### Actual Behaviour

Currently the name for the Backoffice System in the architecture.png should be "SAP Hana 4" (https://github.com/adobe/commerce-integration-starter-kit/raw/main/architecture.png)

#### Steps to Reproduce

Check the image that is also used in the [README.md](https://github.com/adobe/commerce-integration-starter-kit/blob/main/README.md).

**Comment by rojoangel** [comment]
Thanks for raising this issue.
Since the starter kit is generic and not back-office specific, instead of doing a rename in the diagrams I will remove any reference to SAP S/4HANA.
